Repository os2display/display-templates, pull requests merged in 2025-03, with the labels that each got.

#165 New feed source: Eventdatabasen v2
  CHANGELOG.md
  build/poster-config-develop.json
  build/poster-config-main.json
  build/poster.js
  src/poster/poster.js
  src/slides.js
Labels: bug

#172 Added github PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: documentation

#166 Theme: Add css for instagram template
  CHANGELOG.md
  src/themes/aakb.css
Labels: enhancement

#167 Fixed instagram template issue when maxEntries is not a number
  CHANGELOG.md
  build/instagram-feed-config-develop.json
  build/instagram-feed-config-main.json
  build/instagram-feed.js
  src/instagram-feed/instagram-feed.js
  src/slides.js
Labels: bug

#171 Travel: Remove info about changes to routes
  CHANGELOG.md
  build/travel-config-develop.json
  build/travel-config-main.json
  build/travel.js
  src/travel/travel.js
Labels: enhancement
